---
title: "mdom_timelines"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs, message = FALSE, warning=FALSE}
library(dplyr)
library(tidyverse)

library(scales)

library(akima)
#library(asbio)
#library(tmap)         # raster + vector layers
#library(raster)       # Main raster library
#library(tidyverse)    # our old friend
#library(sf)           # to work with simple features data
#library(mapview)
library(openxlsx)
library(class)
library(RANN)
library("survival")
library("Hmisc")

library(MARSS)
library(utils)


#install.packages("survival")

library(lattice)
#install.packages("latticeExtra")


library(plyr)
library(quantreg)

library(survival)
library(Hmisc)
library(lubridate)
#install.packages("installr")
#library(installr)
```
## R Markdown

```{r timeline_import, message=FALSE, warning=FALSE}
bt_sum_mdom <- read_csv("Blob_table_summary_CAICEmdom.csv") %>% 
  filter(!is.na(File_num))
  


bt_sum_mdom <- bt_sum_mdom %>% mutate(r_date =    mdy_hm(SS_startdate)) %>% 
  mutate(run_date = as.Date(gsub("GCxGC_","",File_num), "%Y%m%d"))

make_file_name <- function(date_string) {
  file_start <- "MDOM_blobtables/"
  file_end <- ".csv"
  full_name <- paste(file_start,date_string,file_end, sep = "")
  return(full_name)
  
}

read_bt_files <- function(fi_name_short) {
  
  fi_name <- make_file_name(fi_name_short)
  temp_bt <<- read_csv(file = fi_name)
  temp_bt <- temp_bt %>% mutate(File_num = fi_name_short)
  temp_bt <<- temp_bt
  return(temp_bt)
}

make_massive_table <- function(summary_table){
 
  M <- read_bt_files(as.character(summary_table$File_num[1]))

  for(i in 2:length(summary_table$File_num)){
    t <- read_bt_files(as.character(summary_table$File_num[i]))
    Mnew <- rbind(M, t)
    M <- Mnew
    print(i)
  }
  M_t <<- M
}

make_massive_table(bt_sum_mdom)


M_t_full_mdom <- M_t %>% 
  left_join(bt_sum_mdom, by = "File_num") 

names(M_t_full_mdom) <- make.names(names(M_t_full_mdom),unique = TRUE) 



```

```{r, message=FALSE, warning=FALSE}
Match_factor_floor <- 750
Reverse_match_factor_floor <- 100
LRI_diff_floor <- 6




fb_match_factor_floor <- 600
fb_reverse_match_factor_floor <- 100
IS_lib_name <- "caice_ssi"
# lib_remove_1 <- "caice_ssa_0805_0612"
# lib_remove_2 <- "caice_ssa_0803_1728"
# lib_remove_3 <- "caice_ssa_0803_oil_1728"
# lib_remove_4 <- "amzi0503_b"
FB_lib_name <- "caice_mdom_meohblank_nottraced"

rt2_floor <- .15 # note: check on this, but for purposes of indexing retention times in 2d this is important

# creating a column of the differences in linear retention indecies so that poor matches can be screened out
M_t_LRI_mdom <- M_t_full_mdom %>% mutate(LRI_diff = abs(Library.RI-LRI.I)) %>% 
  mutate(LRI_diff = replace_na(LRI_diff, -999))


# # getting rid of things that should be removed
# remove_match <- M_t_LRI %>% 
#   filter(Library.Name == lib_remove_1 | Library.Name == lib_remove_2 | Library.Name == lib_remove_3 | Library.Name == lib_remove_4)


# identifying the internal standard
IS_goodmatch_mdom <- M_t_LRI_mdom %>% 
  filter(Library.Name == IS_lib_name | Library.Name == "-") %>% 
  filter(LRI_diff < LRI_diff_floor | Description== "match") %>% 
  filter(Library.Match.Factor > Match_factor_floor| Description== "match")  

FB_goodmatch <- M_t_LRI_mdom %>%
  filter(Library.Name == FB_lib_name) %>%
  filter(LRI_diff < LRI_diff_floor) %>%
  filter(Library.Match.Factor > fb_match_factor_floor)

FB_okmatch <- M_t_LRI_mdom %>%
  filter(Library.Name == FB_lib_name) %>%
  filter(Library.Match.Factor> fb_match_factor_floor-100) %>%
  anti_join(FB_goodmatch)
  
IS_okmatch <- M_t_LRI_mdom %>% 
  filter(Library.Name == IS_lib_name | Library.Name == "-") %>%
  filter(Library.Match.Factor > Match_factor_floor-100)  %>% 
  anti_join(IS_goodmatch_mdom)

small_poorlymatched <- M_t_LRI_mdom %>% 
  filter(Library.Match.Factor < Match_factor_floor) %>% 
  filter(Volume < 200)

btz4 <- small_poorlymatched %>% 
  filter(Compound.Name == "20200803_1535_blob_958_")
# 33/70 in here, makes sense

M_t_all_analytes <- M_t_LRI_mdom %>% 
  #anti_join(FB_goodmatch) %>% 
  anti_join(IS_goodmatch_mdom) %>% 
  #anti_join(FB_okmatch) %>% 
  anti_join(IS_okmatch) %>% 
  #anti_join(remove_match) %>% 
  anti_join(small_poorlymatched) %>% 
  filter(LRI.I > 1200) 



## Getting rid of things that existed and were well matched in the tap water blank

  
M_t_analyte_unique_mdom <- M_t_all_analytes %>% 
  arrange((r_date)) %>% 
  filter(Library.Name != IS_lib_name) %>% 
  filter(LRI_diff < LRI_diff_floor| Description == "match") %>% 
  filter(Library.Match.Factor > Match_factor_floor | Description == "match") %>% 
  #filter(Library.Reverse.Match.Factor > Reverse_match_factor_floor) %>% 
  arrange(desc(Volume)) %>% 
  arrange(Compound.Name) %>% 
  arrange(r_date) %>% 
  distinct(Compound.Name, r_date, .keep_all = TRUE)
```



```{r}

# tracking the mass of all of the analytes before bad matches are screened out for later analysis of library performance
M_t_all_analytes_volcount <- M_t_all_analytes %>% 
  group_by(File_num) %>% 
  dplyr::summarise(rawvol = sum(Volume))


# tracking the number of all analutes in
M_t_all_analytes_ncount <- M_t_all_analytes %>% 
  dplyr::count(File_num) %>% 
  dplyr::rename(total_num_analyte = n)

M_t_match_analytes_volcount <- M_t_analyte_unique_mdom %>% 
  group_by(File_num) %>% 
  dplyr::summarise(rawvol_match = sum(Volume))

M_t_match_analytes_ncount <- M_t_analyte_unique_mdom %>% 
  dplyr::count(File_num) %>% 
  dplyr::rename(total_num_analyte_match = n)

M_t_analyte_summary <- M_t_all_analytes_volcount %>% 
  left_join(M_t_all_analytes_ncount) %>% 
  left_join(M_t_match_analytes_volcount) %>% 
  left_join(M_t_match_analytes_ncount) %>% 
  mutate(perct_nfound = (total_num_analyte_match/total_num_analyte)*100) %>% 
  mutate(perct_volfound = (rawvol_match/rawvol)*100)

compound_pop <- M_t_analyte_unique_mdom %>% 
  dplyr::count(Compound.Name) %>% 
  dplyr::rename(comp.n = n) %>% 
  mutate(pct_of_samp = (comp.n/max(comp.n)*100))

#table(compound_pop$comp.n)
#hist(compound_pop$comp.n)

# 
# #note: potential issue with screening out bad fb matches eek
# M_t_analyte_count <- M_t_full %>%
#   filter(Library.Name != "amzi0503_b") %>%
#   filter(Library.Name != "fb_amz_compiled_t") %>%
#   count(File_num) %>%
#   rename(total_num_analyte = n)

M_t_analyte_count <- M_t_all_analytes %>% 
  dplyr::count(File_num) %>%
  dplyr::rename(total_num_analyte = n)
# 
# # counting the number of unique analytes in each image
num_analyte_unique_mdom <- M_t_analyte_unique_mdom %>%
  dplyr::count(File_num) %>%
  dplyr::rename(unique.analyte = n)

# counting the number based percent of compounds being traced in all 
perct_comps_traced <- num_analyte_unique_mdom %>% 
   left_join(M_t_analyte_count) %>% 
   mutate(pct_found = unique.analyte/total_num_analyte)
# 
#perct_comps_traced %>%
#  ggplot(aes(y = pct_found))+
#  geom_boxplot()

summary(perct_comps_traced$pct_found)


M_t_analyte_unique_mdom <- M_t_analyte_unique_mdom %>% left_join(num_analyte_unique_mdom)

compound_pop <- M_t_analyte_unique_mdom %>% 
  dplyr::count(Compound.Name) %>% 
  dplyr::rename(comp.n = n) %>% 
  mutate(pct_of_samp = (comp.n/max(comp.n)*100))

table(compound_pop$comp.n)

hist(compound_pop$pct_of_samp, 
     main = paste("Histogram of", nrow(compound_pop), "Traced Compounds\nOver Seascape Bloom 3"),
     xlab = "Percent Occurence Above Detection Limits",
     col = "grey")

MDOM_sample_cumsum <- M_t_analyte_unique_mdom %>% 
  group_by(File_num) %>% 
  dplyr::summarise(File_vol = sum(Volume))


M_t_analyte_unique_mdom <- M_t_analyte_unique_mdom %>% 
  left_join(compound_pop) %>% 
  left_join(MDOM_sample_cumsum) %>% 
  mutate(Volume_Fraction = Volume/File_vol)


M_t_analyte_unique_mdom %>% 
  mutate(char_comp_n = as.integer(round(pct_of_samp, 0))) %>% 
  group_by(char_comp_n) %>% 
  dplyr::summarise(avg_vol_byn = mean(Volume)) %>% 
  ggplot(aes(x = char_comp_n, y = avg_vol_byn)) +
  geom_col()+
  labs(title = "Average Blob Volume by Library Match Frequency")+
  xlab("Percent of Samples with Positive Library Match")+
  ylab("Average Blob Volume")

```

```{r fig.width=2, fig.height=3, warning = FALSE}


M_t_analyte_summary %>% 
  ggplot(aes(y = perct_nfound))+
  geom_boxplot(fill = "pink") + 
  theme_bw()+
  ylab("Percent of Analytes Assigned to \nLibrary Match")

M_t_analyte_summary %>% 
  ggplot(aes(y = perct_volfound))+
  geom_boxplot(fill = "pink") + 
  theme_bw()+
  ylab("Percent of Analyte Volume Assigned to \nLibrary Match")

summary(M_t_analyte_summary$perct_volfound)

```

```{r}

unique_tracing <- M_t_analyte_unique_mdom %>% 
  arrange(r_date)

unique_tag <- 
  unique_tracing %>% 
  filter(File_num == bt_sum_mdom$File_num[1]) %>% 
  mutate(is_unique_prior = NA) %>% 
  dplyr::select(Compound.Name, File_num, is_unique_prior)


for(i in 2:nrow(bt_sum_mdom)){
  
  
  
  previous_file_i <- bt_sum_mdom$File_num[i-1]
  file_i <- bt_sum_mdom$File_num[i]
  
  prev_compounds <- unique_tracing %>% 
    filter(File_num == previous_file_i) %>% 
    mutate(is_unique_prior = FALSE) %>% 
    dplyr::select(Compound.Name, is_unique_prior)
  
  compounds_i <- unique_tracing %>% 
    filter(File_num== file_i)
  
  
  unique_tag_t <- compounds_i %>% 
    left_join(prev_compounds, by = "Compound.Name") %>% 
    dplyr::select(Compound.Name, File_num, is_unique_prior)
  
  unique_tag <- rbind(unique_tag, unique_tag_t)
    
  
}

unique_tracing_c <- unique_tracing %>% 
  left_join(unique_tag, by = c("Compound.Name", "File_num")) %>% 
  mutate(unique_log = is.na(is_unique_prior)) %>% 
  mutate(unique_vol = unique_log * Volume) 


avg_unique = sum(unique_tracing_c$unique_vol)/sum(unique_tracing_c$Volume)

```

```{r}
unique_tracing_c %>% 
  #filter(IOP == 2) %>% 
  mutate(ones = 1) %>% 
  ggplot(aes(fill = unique_log, y = ones, x = r_date))+
  geom_bar(position = "stack", stat = "identity")+
  ylab("Analyte Count")




unique_tracing_c %>% 
  #filter(IOP == 2) %>% 
  mutate(ones = 1) %>% 
  ggplot(aes(fill = unique_log, y = Volume, x = r_date))+
  geom_bar(position = "stack", stat = "identity")+
  ylab("Analyte Raw Volume")+
  xlab("Dry Season GoAmazon Date")+
  scale_fill_manual(name = "Unique Compared\n to Previous Sample", values=c("blue", "green"))+
  theme(axis.text.x = element_text(size=14), axis.text.y = element_text(size=14), axis.text=element_text(size=12),
        axis.title=element_text(size=14))


  
  
```
```{r pressure, importing chemical info}

compiled_comp_info_mdom <- read_csv("Compiled_Compoundinfo_Blobtable_SS_mdom.csv")

compiled_comp_info_mdom.findable <- compiled_comp_info_mdom %>% 
  filter(Library.Match.Factor_NISTmain> 800) %>% 
  mutate(Identifiable = TRUE) %>% 
  dplyr::select(Compound.Name, Identifiable)

#id.tags <- data.frame("Identifiable"= c(TRUE, NA), ID)

compiled_comp_info_mdom <- compiled_comp_info_mdom %>% 
  left_join(compiled_comp_info_mdom.findable) %>% 
  mutate(tic = 1)

compiled_comp_info_mdom %>% 
  ggplot(aes(x = "", y = tic, fill = Identifiable)) + 
  geom_col()+
  coord_polar("y", start = 0)+
  theme_classic() +
  theme(plot.title = element_text(hjust=0.5),
        axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
  labs(fill = "",
       x = NULL,
       y = NULL) + 
  ggtitle("991 Novel and Identifiable Submicron SSA Compounds- SeaScape")

```


```{r}
mdom_cumsum_raw <- M_t_analyte_unique_mdom%>% 
  mutate(tic = 1) %>% 
  group_by(Compound.Name) %>% 
  dplyr::summarise(raw_cumsum = sum(Volume), num_obs = sum(tic)) %>% 
  mutate(pct_obs = num_obs/nrow(bt_sum_mdom)) %>% 
  arrange(desc(raw_cumsum))





M_t_analyte_unique_mdom_info <- M_t_analyte_unique_mdom %>% 
  left_join(mdom_cumsum_raw, by = "Compound.Name") %>% 
  left_join(compiled_comp_info_mdom, by = "Compound.Name") %>% 
  left_join(compiled_comp_info_mdom.findable, by = "Compound.Name")

for(i in 1:nrow(compiled_comp_info_mdom.findable)){
  findable_c <- compiled_comp_info_mdom$Compound.Name[i]
  
  f1 <- M_t_analyte_unique_mdom_info %>% 
    filter(Compound.Name == findable_c) %>% 
    ggplot(aes(x = r_date, y = Volume, color = Compound.Name_NISTmain))+
    geom_line()
  
  print(f1)
  
  
  
  
}

```

```{r IS_mapping1}
# note: unlike sample analytes, internal standard compounds are frequently split vertically into multiple blobs because of the high volume.  In order to account for this, I am summing all blobs together that meet the high match criteria and are very close in the first dimension.
IS_unique_mdom <- IS_goodmatch_mdom %>% 
  group_by(Compound.Name, File_num) %>% 
  dplyr::summarise(Volume_tot = sum(Volume)) %>% 
  filter(Compound.Name != "glucose-13C6") %>% 
  filter(Compound.Name != "dC14") %>% 
  filter(Compound.Name != "d-C22 acid, TMS") 


fixing <- data.frame(table(IS_unique_mdom$Compound.Name)) %>% 
  mutate(Compound.Name = Var1)

IS_tofix <- IS_unique_mdom %>% 
  left_join(fixing) %>% 
  filter(Freq < 8) %>% 
  left_join(bt_sum_mdom, by = "File_num")

IS_unique_c <- IS_unique_mdom %>% 
  mutate(tic = 1) %>% 
  group_by(File_num) %>% 
  dplyr::summarise(ticsum = sum(tic))

c<- data.frame(table(IS_unique_mdom$Compound.Name))

# note: this is not knitting, not sure why but did temporary work around
IS_positions_mdom <- IS_goodmatch_mdom %>%
  filter(Compound.Name != "glucose-13C6") %>%
  filter(Compound.Name != "dC14") %>%
  group_by(Compound.Name, File_num) %>%
  #summarise(LRI_avg = mean(LRI.I), RI2 = min(Retention.II..sec.-rt2_floor))
  dplyr::summarise(LRI_avg = mean(LRI.I), RI2 = min(Retention.II..sec. - rt2_floor))
# 
# IS_positions_knit <- write.csv(IS_positions, "IS.pos.knit.csv")

# IS_positions <- read.csv("IS.pos.knit.csv") %>% 
#   dplyr::select(-X)
#   

IS_avg_vols_toadd <- IS_unique_mdom %>% 
  group_by(Compound.Name) %>% 
  dplyr::summarise(IS_avgvol = mean(Volume_tot), IS_medvol = median(Volume_tot)) %>% 
  left_join(IS_unique_mdom) %>% 
  mutate(IS_mean_norm = Volume_tot / IS_avgvol) %>%
  mutate(IS_med_norm = Volume_tot / IS_medvol) %>% 
  dplyr::select(Compound.Name, File_num, IS_mean_norm)

write.csv(IS_avg_vols_toadd, "IS_avg_vols_mdom.csv")

IS_unique_pos <- IS_unique_mdom %>% 
  left_join(IS_positions_mdom) %>% 
  left_join(IS_avg_vols_toadd)



# IS_test1 <- IS_unique_pos %>% 
#   filter(File_num == "GCxGC_20200803_1001")
# 
# IS_1_vol <- IS_test1$Volume_tot
# RI1 <- IS_test1$LRI_avg
# RI2 <- IS_test1$RI2

# IS_1_pos <- IS_test1 %>% 
#   ungroup() %>% 
#   dplyr::select("LRI_avg", "RI2")
# IS_positions_202008061332 <- read.csv("GCxGC_20200806_1332.h5_img01_IS_selected_positions_Blob_Table.csv")
# IS_rt2 <- IS_positions_202008061332 %>% 
#   dplyr::select(Compound.Name, Retention.II..sec.)

# IS_positions <- IS_goodmatch %>% 
#   filter(Compound.Name != "glucose-13C6") %>% 
#   filter(Compound.Name != "dC14") %>% 
#   group_by(Compound.Name, File_num) %>% 
#   #summarise(LRI_avg = mean(LRI.I), RI2 = min(Retention.II..sec.-rt2_floor))
#   summarise(LRI_avg = mean(LRI.I), RI2 = min(Retention.II..sec. - rt2_floor))


IS_positions_mdom_avg <- IS_positions_mdom %>% 
  group_by(Compound.Name) %>% 
  dplyr::summarise(LRI_avg_all = mean(LRI_avg, na.rm = TRUE), RI2_all = mean(RI2, na.rm = TRUE)) 


write.csv(IS_positions_mdom_avg, "IS_positions_mdom_avg.csv")


IS_avg_vols_mdom <- IS_unique_mdom %>% 
  group_by(Compound.Name) %>% 
  dplyr::summarise(IS_avgvol = mean(Volume_tot), IS_medvol = median(Volume_tot)) %>% 
  left_join(IS_unique_mdom) %>% 
  mutate(IS_mean_norm = Volume_tot / IS_avgvol) %>%
  mutate(IS_med_norm = Volume_tot / IS_medvol) %>% 
  left_join(bt_sum_mdom)

IS_avg_vols_mdom.s <- IS_unique_mdom %>% 
  group_by(Compound.Name) %>% 
  dplyr::summarise(IS_avgvol = mean(Volume_tot), IS_medvol = median(Volume_tot))

write.csv(IS_avg_vols_mdom.s, "IS_mean_med_vols_mdombloom3_samples2.csv")

IS_cat <- read.csv("IS_withcat.csv")
IS_cat <- IS_cat %>% 
  dplyr::select(-X)

IS_avg_vols_mdom <- IS_avg_vols_mdom %>% 
  left_join(IS_cat)
  

IS_just_one_IS <- IS_avg_vols_mdom %>% 
  filter(Compound.Name == "dC24") %>% 
  dplyr::select(File_num, dalk_norm=IS_mean_norm) 

IS_stability <- IS_avg_vols_mdom %>% 
  left_join(IS_just_one_IS) %>% 
  left_join(IS_positions_mdom_avg)

IS_stability %>% 
  ggplot(aes(x = dalk_norm, y = IS_mean_norm, color = F_group_cat))+
  geom_point()+
  ylim(0, 2) +
  xlim(0,2)
  



IS_avg_vols_mdom %>% ggplot(aes(x = r_date, y = IS_med_norm, color = Compound.Name)) +
  geom_point()
  

IS_avg_vols_mdom %>% ggplot(aes(x = r_date, y = Volume_tot, color = Compound.Name)) +
  geom_point()

IS_stability %>% 
  ggplot(aes(x = LRI_avg_all, y = IS_mean_norm, color = r_date))+
  geom_point()

IS_stability %>% 
  ggplot(aes(x = LRI_avg_all, y = Volume_tot, color = r_date))+
  geom_point()

IS_stability %>% 
  ggplot(aes(x = RI2_all, y = IS_mean_norm, color = r_date))+
  geom_point()

IS_stability %>% 
  ggplot(aes(x = RI2_all, y = Volume_tot, color = r_date))+
  geom_point()

IS_stability %>% 
  ggplot(aes(x = LRI_avg_all, y = IS_mean_norm, color = F_group_cat))+
  geom_point()

IS_stability %>% 
  ggplot(aes(x = LRI_avg_all, y = Volume_tot, color = F_group_cat))+
  geom_point()

IS_stability %>% 
  ggplot(aes(x = RI2_all, y = IS_mean_norm, color = F_group_cat))+
  geom_point()

IS_stability %>% 
  ggplot(aes(x = RI2_all, y = Volume_tot, color = F_group_cat))+
  geom_point()
```


```{r IS_mapping2}
LRI_weight = 10
LRII_weight = 1

LRI1_avg = mean(IS_positions_mdom_avg$LRI_avg_all, na.rm = TRUE)
LRI2_avg = mean(IS_positions_mdom_avg$RI2_all)

IS_positions_mdom_avg <- IS_positions_mdom_avg %>% 
  mutate(relative_LRI = (LRI_avg_all/LRI1_avg)*LRI_weight) %>% 
  mutate(relative_LRI2 = (RI2_all/LRI2_avg)*LRII_weight)

write.csv(IS_positions_mdom_avg, "IS_positions_mdom_avg_rel.csv")

Analyte_positions_mdom_trial <- M_t_analyte_unique_mdom %>% 
  group_by(Compound.Name, File_num) %>% 
  dplyr::summarise(LRI_avg = mean(LRI.I), RI2 = min(Retention.II..sec. - rt2_floor))

# note filtering out three small blobs outside of RI window

Analyte_positions_mdom <- M_t_analyte_unique_mdom %>% 
  filter(!is.na(LRI.I)) %>% 
  group_by(Compound.Name) %>% 
  dplyr::summarise(LRI_avg = mean(LRI.I, na.rm = TRUE), RI2 = median(Retention.II..sec. - rt2_floor))
  

Analyte_positions_mdom <- Analyte_positions_mdom %>% 
  mutate(relative_LRI = (LRI_avg/LRI1_avg)*LRI_weight) %>% 
  mutate(relative_LRI2 = (RI2/LRI2_avg)*LRII_weight)

# checking to make sure that the ranges match up, eg back end checking that same norm method used on moth IS and analyte positions
summary(IS_positions_mdom_avg$relative_LRI)
summary(Analyte_positions_mdom$relative_LRI)
summary(IS_positions_mdom_avg$relative_LRI2)
summary(Analyte_positions_mdom$relative_LRI2)

Analyte_pos_mdom_short <- Analyte_positions_mdom %>% 
  dplyr::select(relative_LRI, relative_LRI2)

IS_pos_mdom_short <- IS_positions_mdom_avg %>% 
  dplyr::select(relative_LRI, relative_LRI2)

#knn(IS_pos_short, Analyte_pos_short, cl=IS_pos_short$Compound.Name, k=1, l=0)

#Old method, only using 1 nearest
#testnn <- nn2(IS_pos_short, query = Analyte_pos_short, treetype = "kd", searchtype = "standard", k=1)

# note 1.19 is the min radius at which every compound has at least one nearest
testnn <- nn2(IS_pos_mdom_short, query = Analyte_pos_mdom_short, treetype = "kd", searchtype = "radius", k=3, radius = 3.9)


Analyte_IS_Index <- data.frame(testnn$nn.idx)
# old method only using 1 nearest
# Analyte_pos_ad <- data.frame(Compound.Name = Analyte_positions$Compound.Name, IS_index = Analyte_IS_Index)

Analyte_pos_ad <- data.frame(Compound.Name = Analyte_positions_mdom$Compound.Name, IS_index1 = Analyte_IS_Index$X1, IS_index2 = Analyte_IS_Index$X2, IS_index3 = Analyte_IS_Index$X3)

# old method with only 1 IS
# Analyte_with_IS <- Analyte_pos_ad %>% 
#   mutate(IS_appropriate = IS_positions_avg$Compound.Name[IS_index])

# Analyte_with_IS <- Analyte_pos_ad %>% 
#   mutate(IS_appropriate1 = IS_positions_avg$Compound.Name[IS_index1]) %>% 
#   mutate(IS_appropriate2 = IS_positions_avg$Compound.Name[IS_index2]) %>% 
#   mutate(IS_appropriate3 = IS_positions_avg$Compound.Name[IS_index3])

Analyte_with_IS_mdom <- Analyte_pos_ad %>% 
  mutate(IS_appropriate1 = NA) %>% 
  mutate(IS_appropriate2 = NA) %>% 
  mutate(IS_appropriate3 = NA)

for(i in 1:nrow(Analyte_with_IS_mdom)){
  t_isind_1 <- Analyte_with_IS_mdom$IS_index1[i]
  t_isind_2 <- Analyte_with_IS_mdom$IS_index2[i]
  t_isind_3 <- Analyte_with_IS_mdom$IS_index3[i]
  
  if(t_isind_1 > 0){
  t_isap_1 <- IS_positions_mdom_avg$Compound.Name[t_isind_1]
  }else{
    t_isap_1 <- NA
  }
  
  if(t_isind_2 > 0){
  t_isap_2 <- IS_positions_mdom_avg$Compound.Name[t_isind_2]
  }else{
    t_isap_2 <- NA
  }
  
  if(t_isind_3 > 0){
  t_isap_3 <- IS_positions_mdom_avg$Compound.Name[t_isind_3]
  }else{
    t_isap_3 <- NA
  }
  
  
  
  Analyte_with_IS_mdom$IS_appropriate1[i] <- t_isap_1
  Analyte_with_IS_mdom$IS_appropriate2[i] <- t_isap_2
  Analyte_with_IS_mdom$IS_appropriate3[i] <- t_isap_3
  
}

# Analyte_with_IS_positions <- Analyte_with_IS %>% 
#   left_join(Analyte_positions) %>% 
#   left_join(IS_positions_avg, by = c("IS_appropriate"= "Compound.Name"))

Analyte_with_IS_positions_mdom <- Analyte_with_IS_mdom %>% 
  left_join(Analyte_positions_mdom) %>% 
  left_join(IS_positions_mdom_avg, by = c("IS_appropriate1"= "Compound.Name")) %>% 
  left_join(IS_positions_mdom_avg, by = c("IS_appropriate2"= "Compound.Name")) %>% 
  left_join(IS_positions_mdom_avg, by = c("IS_appropriate3"= "Compound.Name"))

M_t_analyte_withIS_mdom <- M_t_analyte_unique_mdom %>% 
  left_join(Analyte_with_IS_mdom) %>% 
  mutate(IS_vol1= -999*(LRI.I/LRI.I)) %>% 
  mutate(IS_mean_norm1= -999*(LRI.I/LRI.I)) %>% 
  mutate(IS_vol2= -999*(LRI.I/LRI.I)) %>% 
  mutate(IS_mean_norm2= -999*(LRI.I/LRI.I)) %>% 
  mutate(IS_vol3= -999*(LRI.I/LRI.I)) %>% 
  mutate(IS_mean_norm3= -999*(LRI.I/LRI.I)) %>% 
  mutate(IS_vol_dalk= -999*(LRI.I/LRI.I)) %>% 
  mutate(IS_mean_norm_dalk= -999*(LRI.I/LRI.I))

# old- only 1 IS
# M_t_analyte_withIS <- M_t_analyte_unique %>% 
#   left_join(Analyte_with_IS) %>% 
#   mutate(IS_vol= -999*(LRI.I/LRI.I)) %>% 
#   mutate(IS_mean_norm= -999*(LRI.I/LRI.I)) 


# for(i in 1:nrow(M_t_analyte_withIS)){
#   
#   
#   IS_name = M_t_analyte_withIS$IS_appropriate[i]
#   File_num_t = M_t_analyte_withIS$File_num[i]
#   
#   IS_indicated <- IS_stability %>% 
#     filter(Compound.Name == IS_name) %>% 
#     filter(File_num == File_num_t)
#   
#   M_t_analyte_withIS$IS_vol[i] <-IS_indicated$Volume_tot[1]
#   M_t_analyte_withIS$IS_mean_norm[i] <-IS_indicated$IS_mean_norm[1]
#   
#   
# }

for(i in 1:nrow(M_t_analyte_withIS_mdom)){
  
  
  
  IS_name1 = M_t_analyte_withIS_mdom$IS_appropriate1[i]
  IS_name2 = M_t_analyte_withIS_mdom$IS_appropriate2[i]
  IS_name3 = M_t_analyte_withIS_mdom$IS_appropriate3[i]
  
  
  
  
  File_num_t = M_t_analyte_withIS_mdom$File_num[i]
  
  IS_indicated1 <- IS_stability %>% 
    filter(Compound.Name == IS_name1) %>% 
    filter(File_num == File_num_t)
  
  M_t_analyte_withIS_mdom$IS_vol1[i] <-IS_indicated1$Volume_tot[1]
  M_t_analyte_withIS_mdom$IS_mean_norm1[i] <-IS_indicated1$IS_mean_norm[1]
  
  IS_indicated2 <- IS_stability %>% 
    filter(Compound.Name == IS_name2) %>% 
    filter(File_num == File_num_t)
  
  M_t_analyte_withIS_mdom$IS_vol2[i] <-IS_indicated2$Volume_tot[1]
  M_t_analyte_withIS_mdom$IS_mean_norm2[i] <-IS_indicated2$IS_mean_norm[1]
  
  IS_indicated3 <- IS_stability %>% 
    filter(Compound.Name == IS_name3) %>% 
    filter(File_num == File_num_t)
  
  M_t_analyte_withIS_mdom$IS_vol3[i] <-IS_indicated3$Volume_tot[1]
  M_t_analyte_withIS_mdom$IS_mean_norm3[i] <-IS_indicated3$IS_mean_norm[1]
  
}

# 
# M_t_analyte_withIS <- M_t_analyte_withIS %>% 
#   mutate(vol_is_normnorm = Volume/IS_mean_norm) %>% 
#   mutate(vol_is_rawnorm = Volume/IS_vol)
#   

# note- this step is not working
# M_t_analyte_withIS <- M_t_analyte_withIS %>% 
#   mutate(IS_vol = mean(c(IS_vol1, IS_vol2, IS_vol3), na.rm = TRUE)) %>% 
#   mutate(IS_mean_norm = mean(c(IS_mean_norm1, IS_mean_norm2, IS_mean_norm3), na.rm = TRUE))

for(i in 1:nrow(M_t_analyte_withIS_mdom)){
  
  isvols_raw <- c(M_t_analyte_withIS_mdom$IS_vol1[i], M_t_analyte_withIS_mdom$IS_vol2[i], M_t_analyte_withIS_mdom$IS_vol3[i])
  
  M_t_analyte_withIS_mdom$IS_vol[i] = mean(isvols_raw, na.rm = TRUE)
  
  isvols_norm <- c(M_t_analyte_withIS_mdom$IS_mean_norm1[i], M_t_analyte_withIS_mdom$IS_mean_norm2[i], M_t_analyte_withIS_mdom$IS_mean_norm3[i])
  
  M_t_analyte_withIS_mdom$IS_mean_norm[i] = mean(isvols_norm, na.rm = TRUE)
  
}


M_t_analyte_withIS_mdom <- M_t_analyte_withIS_mdom %>% 
  mutate(vol_is_normnorm = Volume/IS_mean_norm) %>% 
  mutate(vol_is_rawnorm = Volume/IS_vol) 


IS_problems <- M_t_analyte_withIS_mdom %>% 
  filter(is.na(IS_appropriate1))

File_norm_totorg_mdom <- M_t_analyte_withIS_mdom %>% 
  group_by(r_date) %>% 
  dplyr::summarise(vol_normnorm_total = sum(vol_is_normnorm), vol_rawnorm_total = sum(vol_is_rawnorm))

File_norm_totorg_mdom %>% 
  ggplot(aes(x = r_date, y = vol_rawnorm_total))+
  geom_point()

File_norm_totorg_mdom %>% 
  ggplot(aes(x = r_date, y = vol_normnorm_total))+
  geom_point()

M_t_analyte_withIS_mdom <- M_t_analyte_withIS_mdom %>% 
  left_join(File_norm_totorg_mdom) %>% 
  mutate(vol_is_normnorm_totorgnorm = vol_is_normnorm/vol_normnorm_total)


```
DOM seascape methods comarison plot
```{r}
anthroad <- M_t_analyte_withIS_mdom %>% 
  filter(Sample_num == ("MDOM_0724")|Sample_num == ("MDOM_0726")) %>% 
  dplyr::select(Sample_num, Compound.Name, vol_is_rawnorm) %>% 
  spread(Sample_num, vol_is_rawnorm, fill = 0)  %>% 
  mutate(norm_volchange = MDOM_0726 - MDOM_0724) %>% 
  mutate(pct_change = 100*norm_volchange/(MDOM_0726)) %>% 
  left_join(Analyte_positions_mdom) %>% 
  mutate(enhancement_cat = NA)

for(i in 1:nrow(anthroad)){
  if(anthroad$MDOM_0724[i] == 0){
    anthroad$enhancement_cat[i] = "Introduced"
  }else if(anthroad$MDOM_0726[i] == 0){
    anthroad$enhancement_cat[i] = "Removed"
  }else if(anthroad$norm_volchange[i] < 0){
    anthroad$enhancement_cat[i] = "Reduced"
  }else if(anthroad$norm_volchange[i] > 0){
    anthroad$enhancement_cat[i] = "Enhanced"
  }else{
    anthroad$enhancement_cat[i] = "check"
  }
  
  
  
}

anthroad <- anthroad %>% 
  mutate(enhancement_cat.f = as.factor(enhancement_cat))

anthroad$enhancement_cat.f.l <- relevel(anthroad$enhancement_cat.f, "Introduced")


anthroad %>% 
  filter(MDOM_0726 > .00001) %>% 
  ggplot(aes(x = LRI_avg, y = RI2, color = pct_change, size = MDOM_0726, shape = enhancement_cat.f.l))+
  geom_point()+
  xlab("Kovats Index")+
  ylab("Retention Time II (seconds)")+
  ggtitle("Post-Transportation Dissolved Organic Matter:\nComparison to Pre-Transport")+
  scale_size(name = "Compound Signal")+
  scale_shape_manual(name = "Compound Class", values = c(18,17, 16))+
  scale_color_gradientn(name= "Percent Change\nfrom Previous Sample", limits = c(-400, 100),
    colors=c('red4','darksalmon','pink2','dodgerblue1','dodgerblue4'),
    values=c(  -1,       -.005,  0,    .001,      .2)+400/500, na.value = "red4")+
  theme_bw(base_size = 16)
  
  
bioad <- M_t_analyte_withIS_mdom %>% 
  filter(Sample_num == ("MDOM_0730")|Sample_num == ("MDOM_0726")) %>% 
  dplyr::select(Sample_num, Compound.Name, vol_is_rawnorm) %>% 
  spread(Sample_num, vol_is_rawnorm, fill = 0)  %>% 
  mutate(norm_volchange = MDOM_0730 - MDOM_0726) %>% 
  mutate(pct_change = 100*norm_volchange/(MDOM_0730)) %>% 
  left_join(Analyte_positions_mdom) %>% 
  mutate(enhancement_cat = NA)

for(i in 1:nrow(bioad)){
  if(bioad$MDOM_0726[i] == 0){
    bioad$enhancement_cat[i] = "Introduced"
  }else if(bioad$MDOM_0730[i] == 0){
    bioad$enhancement_cat[i] = "Removed"
  }else if(bioad$norm_volchange[i] < 0){
    bioad$enhancement_cat[i] = "Reduced"
  }else if(bioad$norm_volchange[i] > 0){
    bioad$enhancement_cat[i] = "Enhanced"
  }else{
    bioad$enhancement_cat[i] = "check"
  }
  
  
  
}

bioad <- bioad %>% 
  mutate(enhancement_cat.f = as.factor(enhancement_cat))

bioad$enhancement_cat.f.l <- relevel(bioad$enhancement_cat.f, "Introduced")


bioad %>% 
  filter(MDOM_0730 > .00001) %>% 
  ggplot(aes(x = LRI_avg, y = RI2, color = pct_change, size = MDOM_0730, shape = enhancement_cat.f.l))+
  geom_point()+
  xlab("Kovats Index")+
  ylab("Retention Time II (seconds)")+
  ggtitle("Bloom Dissolved Organic Matter:\nComparison to Pre-Bloom")+
  scale_size(name = "Compound Signal")+
  scale_shape_manual(name = "Compound Class", values = c(18,17, 16))+
  scale_color_gradientn(name= "Percent Change\nfrom Previous Sample", limits = c(-400, 100),
    colors=c('red4','darksalmon','pink2','dodgerblue1','dodgerblue4'),
    values=c(  -1,       -.005,  0,    .001,      .2)+400/500, na.value = "red4")+
  theme_bw(base_size = 16)

a.max <- max(anthroad$MDOM_0726)

anthroad.s <- anthroad %>% 
  filter(MDOM_0726>.00001) %>% 
  #mutate(norm_vol = MDOM_0726/a.max) %>% 
  mutate(norm_vol = MDOM_0726) %>% 
  dplyr::select(Compound.Name, norm_vol, norm_volchange, pct_change, LRI_avg, RI2, enhancement_cat.f.l) %>% 
  mutate(plot = as.factor("Post-Transportation Dissolved Organic Matter:\nComparison to Pre-Transport"))
  
b.max <- max(bioad$MDOM_0730)

bioad.s <- bioad %>% 
  filter(MDOM_0730>.00001) %>% 
  #mutate(norm_vol = MDOM_0730/b.max) %>% 
  mutate(norm_vol = MDOM_0730) %>% 
  dplyr::select(Compound.Name, norm_vol, norm_volchange, pct_change, LRI_avg, RI2, enhancement_cat.f.l) %>% 
  mutate(plot = as.factor("Bloom Dissolved Organic Matter:\nComparison to Pre-Bloom"))

kath.plots <- rbind(bioad.s, anthroad.s) 
  

kath.plots$plot.l <- relevel(kath.plots$plot, "Post-Transportation Dissolved Organic Matter:\nComparison to Pre-Transport")

kjm <- kath.plots %>% 
  ggplot(aes(x = LRI_avg, y = RI2, color = norm_volchange, size = norm_vol, shape = enhancement_cat.f.l))+
  geom_point()+
  facet_wrap(plot.l~., strip.position = "top")+
  xlab("Kovats Index")+
  ylab("Retention Time II (seconds)")+
  #ggtitle("Bloom Dissolved Organic Matter:\nComparison to Pre-Bloom")+
  scale_size(name = "Compound Signal")+
  scale_shape_manual(name = "Compound Class", values = c(18,17, 16))+
  scale_color_gradientn(name= "Signal Change\nfrom Previous Sample", limits = c(-45, 25),
    colors=c('red4','darksalmon','pink2','dodgerblue1','dodgerblue4'),
    values=c(  -1,       -.005,  0,    .001,      .5)+45/70, na.value = "red4")+
  # scale_color_gradientn(name= "Percent Increase\nfrom Previous Sample", limits = c(0, 100),
  #   colors=c('grey50','dodgerblue1','dodgerblue4'),
  #   values=c( 0,    20,      100)/100, na.value = "grey50")+
  
  theme_bw(base_size = 16)+
  theme(legend.position = "bottom", legend.direction = "vertical", legend.key.size = unit(1,"line"))
  #guides(color = guide_legend(override.aes = list(size=5)))
  #theme(legend.direction = "vertical", legend.margin = margin(c(5,1,1,10)))

kjm
png("kjm6.png", width=9, height=6,
    units="in", res=1000, pointsize=13)
kjm
dev.off()
  

```


btz quant
```{r}
btz_info.mdom <- read_csv("Benzothiazoles_Combined_info_trimmed.csv")
btz_qf <- read_csv("btz_quantfactors.csv")

btz_mdom_list <- btz_info.mdom %>% 
  filter(!is.na(MDOM_name)) %>% 
  dplyr::select(MDOM_name, My_Name, Quant_Proxy) %>% 
  left_join(btz_qf) %>% 
  mutate(keep = 1)

mdom_amt_persamp <- 50 #ug
unit <- 1000 #ug/mg, becuase mdom conc are in ug
#pun_per_f <- 22.536 
M_t_analyte_withIS_mdom.btz <- M_t_analyte_withIS_mdom %>% 
  left_join(btz_mdom_list, by = c("Compound.Name"= "MDOM_name")) %>% 
  filter(keep ==1) %>% 
  mutate(ng_per_ug = (vol_is_rawnorm/QF_mean)/mdom_amt_persamp) %>% 
  mutate(ng_per_L = ng_per_ug*unit*mdom_conc)

M_t_analyte_withIS_mdom.btz %>% 
  ggplot(aes(x = r_date, y = ng_per_L, fill = My_Name)) +
  geom_col()



btz_mean_conc.mdom <- M_t_analyte_withIS_mdom.btz %>% 
  dplyr::select(My_Name, r_date, ng_per_L) %>% 
  spread(My_Name, ng_per_L, fill = 0) %>% 
  gather(key = "My_Name", value = "ng_per_L", -r_date) %>% 
  group_by(My_Name) %>% 
  dplyr::summarise(ng_per_L.mean = mean(ng_per_L)) %>% 
  mutate(ug_per_L.mean = ng_per_L.mean/1e3) 

btz_mean_conc.mdom <- btz_mean_conc.mdom %>% 
  mutate(vol_frac_mdom = ng_per_L.mean/sum(btz_mean_conc.mdom$ng_per_L.mean, na.rm = TRUE))


combined.btz <- btz_mean_conc %>% 
  full_join(btz_mean_conc.mdom) %>% 
  left_join(btz_info.mdom)

btz_mean_conc.mdom.l <- btz_mean_conc.mdom %>% 
  mutate(type = "MDOM") %>% 
  mutate(vol_frac = vol_frac_mdom) %>% 
  dplyr::select(My_Name, vol_frac, type)

btz_mean_conc.l <- btz_mean_conc %>% 
  mutate(type = "SSA") %>% 
  mutate(vol_frac = vol_frac_ssa) %>% 
  dplyr::select(My_Name, vol_frac, type)   

combined_btz_long <- rbind(btz_mean_conc.l, btz_mean_conc.mdom.l) %>% 
  left_join(btz_info.mdom) %>% 
  filter(!is.na(vol_frac))


#install.packages("quantreg")
combined_btz_long %>% ggplot(aes(x = type, y = water_sol_mg_L, color = Label_name, size = vol_frac*100))+
  geom_point(shape = 0)+
  geom_boxplot(aes(x = type, y = water_sol_mg_L, weight = vol_frac*100))

mdomcomp <- combined_btz_long %>% ggplot(aes(x = type, y = log(water_sol_mg_L), weight = log(vol_frac*100000)))+
  geom_boxplot(range = 8)+
  geom_jitter(aes(x = type, y = log(water_sol_mg_L), color = Label_name, size = vol_frac*100), width = .15)+
  ylab("log(Solubility(mg/L))")+
  xlab("")+
  scale_color_manual(values = c("purple", "blue", "red"))+
  labs(color="Occurence Above\nDetection Limits", size="Percent Benzothiazole\nCarbon Pool")+
  theme_bw()

mdomcomp

png("mdomcomp.png", width=7, height=7,
    units="in", res=600, pointsize=13)
mdomcomp
dev.off()
  

```

making pie graphs

```{r}
combined.btz<- combined.btz %>% 
  arrange(Label_name) 

combined.btz.pie <- combined.btz %>% 
  mutate(ymin.ssa = 0) %>% 
  mutate(ymax.ssa = vol_frac_ssa) %>% 
  mutate(ymin.mdom = 0) %>% 
  mutate(ymax.mdom = vol_frac_mdom) %>% 
  mutate(vol_frac_ssa = replace_na(vol_frac_ssa, 0)) %>% 
  mutate(vol_frac_mdom = replace_na(vol_frac_mdom, 0)) %>% 
  arrange(desc(vol_frac_ssa)) %>% 
  arrange(Label_name) %>% 
  mutate(id = as.factor(row_number()))



for(i in 2:nrow(combined.btz.pie)){
  combined.btz.pie$ymin.ssa[i]= combined.btz.pie$ymax.ssa[i-1]
  combined.btz.pie$ymax.ssa[i]= combined.btz.pie$ymax.ssa[i-1]+ combined.btz.pie$vol_frac_ssa[i]
  
  combined.btz.pie$ymin.mdom[i]= combined.btz.pie$ymax.mdom[i-1]
  combined.btz.pie$ymax.mdom[i]= combined.btz.pie$ymax.mdom[i-1]+ combined.btz.pie$vol_frac_mdom[i]
}

combined.btz.pie.ssa <- combined.btz.pie %>% 
  filter(!is.na(SSA_name)) 

pie.labs.ssa <- combined.btz.pie.ssa %>% 
  dplyr::select(id, My_Name, Plot_color, vol_frac_ssa) %>% 
  mutate(group = "names") %>% 
  mutate(width = 3)

both.t <- combined.btz.pie.ssa %>% 
  group_by(Label_name) %>% 
  summarise(vol_frac_ssa = sum(vol_frac_ssa))

extralabs.ssa <- data.frame(id = as.factor(c(17,18)), My_Name = c("Both Phases", "SSA Only"), Plot_color = c("grey50", "grey90"), vol_frac_ssa = both.t$vol_frac_ssa) %>% 
  mutate(group = "foundwhere") %>% 
  mutate(width = 1)

pie.labs.ssa <- rbind(pie.labs.ssa, extralabs.ssa)

pie.labs.ssa <- pie.labs.ssa %>% 
  mutate(My_Name= as.factor(My_Name)) 

t1 <- ggplot(combined.btz.pie.ssa) + 
  
  geom_rect(aes(fill=id, ymax=ymax.ssa, ymin=ymin.ssa, xmax=3, xmin=0)) +
  #geom_rect(aes(fill=Label_name, ymax=ymax.ssa, ymin=ymin.ssa, xmax=3.5, xmin=3)) +
  #scale_fill_manual(labels = pie.labs.ssa$My_Name, values = pie.labs.ssa$Plot_color)+
  scale_fill_manual(labels = combined.btz.pie.ssa$My_Name, values = combined.btz.pie.ssa$Plot_color)+
  xlim(c(0, 4)) + 
  theme(aspect.ratio=1)# +
  #coord_polar(theta="y")

t2 <- t1 +
  geom_rect(data = combined.btz.pie.ssa, aes(fill = Label_name, ymax=ymax.ssa, ymin=ymin.ssa, xmax=3.5, xmin=3))+
  scale_fill_manual(labels = pie.labs.ssa$My_Name, values = pie.labs.ssa$Plot_color)

t2

blank_theme <- theme_minimal()+
  theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.border = element_blank(),
  strip.text.x = element_text(size = 16),
  panel.grid=element_blank(),
  axis.ticks = element_blank(),
  axis.text = element_blank(),
  legend.text = element_text(size = 16),
  plot.title=element_text(size=14, face="bold")
  )

pie_ssa <- ggplot(pie.labs.ssa)+
  geom_col(aes(x = group, y = vol_frac_ssa, fill = id))+
  scale_fill_manual(name = "", labels = pie.labs.ssa$My_Name, values = pie.labs.ssa$Plot_color)+
  coord_polar("y")+
  blank_theme
pie_ssa
  
png("piessa1.png", width=11, height=7,
    units="in", res=600, pointsize=12)
pie_ssa
dev.off()



```
dom pie chart

```{r}
combined.btz.pie.mdom <- combined.btz.pie %>% 
  filter(!is.na(MDOM_name)) 

pie.labs.mdom <- combined.btz.pie.mdom %>% 
  dplyr::select(id, My_Name, Plot_color, vol_frac_mdom) %>% 
  mutate(group = "names") %>% 
  mutate(width = 3)

both.tt <- combined.btz.pie.mdom %>% 
  group_by(Label_name) %>% 
  summarise(vol_frac_mdom = sum(vol_frac_mdom))

extralabs.mdom <- data.frame(id = as.factor(c(17,19)), My_Name = c("Both Phases", "DOM Only"), Plot_color = c("grey50", "grey15"), vol_frac_mdom = both.tt$vol_frac_mdom) %>% 
  mutate(group = "foundwhere") %>% 
  mutate(width = 1)

pie.labs.mdom <- rbind(pie.labs.mdom, extralabs.mdom)


pie_mdom <- ggplot(pie.labs.mdom)+
  geom_col(aes(x = group, y = vol_frac_mdom, fill = id))+
  scale_fill_manual(name = "", labels = pie.labs.mdom$My_Name, values = pie.labs.mdom$Plot_color)+
  coord_polar("y")+
  blank_theme

png("piemdom1.png", width=11, height=7,
    units="in", res=1000, pointsize=6)
pie_mdom
dev.off()
```

combined pie chart

```{r}
pie.labs.mdom.t <- pie.labs.mdom %>% 
  mutate(facet = "DOM") %>% 
  rename(vol_frac = vol_frac_mdom)

pie.labs.ssa.t <- pie.labs.ssa %>% 
  mutate(facet = "SSA")%>% 
  rename(vol_frac = vol_frac_ssa)

pie.labs.both <- rbind(pie.labs.ssa.t, pie.labs.mdom.t)

pie.labs.both.n <- pie.labs.both %>% 
  distinct(id, .keep_all = TRUE) %>% 
  arrange(id)

btz.pie.b <- ggplot(pie.labs.both, aes(x = group, y = vol_frac, fill = id))+
  geom_col()+
  facet_grid(facets=. ~ facet)+
  scale_fill_manual(name = "", labels = pie.labs.both.n$My_Name, values = pie.labs.both.n$Plot_color)+
  coord_polar(theta="y") +
  blank_theme
  
btz.pie.b

png("pieboth1.png", width=13, height=5,
    units="in", res=1500, pointsize=2)
btz.pie.b
dev.off()


```
now trying stick chart with solubilities

```{r}
btz.stickchart <- btz_info.mdom %>% 
  left_join(btz_mean_conc) %>% 
  left_join(btz_mean_conc.mdom) %>% 
  arrange(My_Name) %>% 
  arrange(desc(water_sol_mg_L)) %>% 
  mutate(My_Name = factor(My_Name, My_Name)) %>% 
  mutate(pcol = factor(Plot_color, Plot_color)) 

colorvals <- (btz.stickchart$Plot_color)#
colorvals <- c("cornflowerblue", "darkslateblue", "deeppink2", "deepskyblue2","greenyellow", 
               "lawngreen", "lightseagreen", "maroon3", "mediumslateblue", "orange1", 
               "palegreen2", "red1", "red4", "turquoise", "violetred4", "yellow1")
colorvals

colornames <- (btz.stickchart$My_Name)
colornames

coeff3 = 1/16

stick <- btz.stickchart %>% 
  #arrange(desc(water_sol_mg_L)) %>% 
  #mutate(My_Name = factor(My_Name, My_Name)) %>% 
  #mutate(plot_color = factor(Plot_color, Plot_color)) %>% 
  ggplot()+
  geom_point(aes(x = My_Name, y = vol_frac_ssa, fill = "SSA", color = Plot_color, stroke = 1.5), size = 4.2, shape = 22)+
  geom_point(aes(x = My_Name, y = vol_frac_mdom, fill = "DOM", color = Plot_color, stroke = 1.5), size = 3.6, shape = 23)+
  scale_fill_manual(name = "", values = c("grey15", "grey90"))+
  scale_color_manual(values = colorvals, labels = colornames)+
  
  geom_point(aes(x = My_Name, y = log(water_sol_mg_L)*coeff3), color = "steelblue4")+
  scale_y_continuous(
    
    # Features of the first axis
    name = "Fraction Benzothiazole\nCarbon Pool",
    
    # Add a second axis and specify its features
    sec.axis = sec_axis(~./coeff3, name="Log Solubility (mg/L)")
  )+
  theme_bw(base_size = 16)+
  theme(axis.title.x.top = element_text(color = "steelblue4"))+
  guides(color = FALSE)+
  xlab("")+
  coord_flip()


png("stick.png", width=7, height=5.5,
    units="in", res=1500, pointsize=2)
stick
dev.off()

btz.stickchart %>% 
  ggplot()+
  geom_point(aes(x = log(water_sol_mg_L), y = vol_frac_ssa, color = My_Name), shape = 15)+
  geom_point(aes(x = log(water_sol_mg_L), y = vol_frac_mdom, color = My_Name), shape = 0)



```




```{r, fig.width=7, fig.height=7}
btz_info <- read_csv("Benzothiazoles_Combined_info.csv")

btzdatemin <- min(bt_sum_bloom3$r_date)
btzdatemax <- max(bt_sum_mdom$r_date)

M_t_analyte_withIS_mdom.btz <- M_t_analyte_withIS_mdom %>% 
  left_join(btz_info, by = c("Compound.Name"= "MDOM_name")) %>% 
  filter(!is.na(NIST_Name)) %>% 
  mutate(My_Name = factor(My_Name,
                levels = c("2(3H)-Benzothiazolone", "Benzothiazole", "3-Methyl-3H-benzothiazol-2-one", "4-Ethyl-5-methylthiazole", "2-(Methylmercapto)benzothiazole", "R-Benzothiazole 1", "Benzothiazole, 2-phenyl- (2)", "5,1-Benzothiazepine-2-one, 3-acetylamino-"))) %>% 
  mutate(r_date_day = date(r_date))

just_btz_mdom_selected <- M_t_analyte_withIS_mdom.btz %>% 
  mutate(amt = vol_is_normnorm) %>% 
  filter(r_date_day == "2019-07-24"| r_date_day == "2019-08-02") %>% 
  dplyr::select(My_Name, r_date_day, water_sol_mg_L, amt, btz_colors) %>% 
  mutate(date_type_factor = paste(r_date_day, "MDOM", sep = " ")) %>% 
  filter(!is.na(My_Name)) %>% 
  filter(!is.na(water_sol_mg_L))


btz_colors_mdom <- btz_info %>% 
  filter(in_mdom == 1)

btz_colors_ssa <- btz_info %>% 
  filter(in_SSA == 1)



M_t_analyte_withIS_mdom.btz %>% 
  ggplot(aes(x = r_date, y = Volume, color = My_Name, fill = log(water_sol_mg_L), order = as.numeric(My_Name)))+
  geom_col(position = "fill", size = 1)+
  scale_fill_gradient(low = "white", high = "black", limits = c(0,8))+
  scale_colour_manual(values = btz_colors_mdom$btz_colors) +
  theme(legend.position = "bottom", legend.box="vertical", legend.margin=margin(), legend.text=element_text(size=8))+
    labs(color="", fill="log(Solubility)")+
  guides(color=guide_legend(nrow=3,byrow=TRUE))+
  ggtitle("Benzothiazoles in MDOM")+
  ylab("Fraction Organic Btz Signal")+
  xlab("")+
  xlim(btzdatemin, btzdatemax)

M_t_analyte_withIS_mdom.btz %>% 
  ggplot(aes(x = r_date, y = Volume, color = My_Name, fill = log(water_sol_mg_L)))+
  geom_col(position = "stack", size = 1)+
  scale_fill_gradient(low = "white", high = "black", limits = c(0,8))+
  scale_colour_manual(values = btz_colors_mdom$btz_colors) +
  theme(legend.position = "bottom", legend.box="vertical", legend.margin=margin(), legend.text=element_text(size=8))+
    labs(color="", fill="log(Solubility)")+
  guides(color=guide_legend(nrow=3,byrow=TRUE))+
  ggtitle("Benzothiazoles in MDOM")+
  ylab("Benzothiazole Signal")+
  xlab("")+
  xlim(btzdatemin, btzdatemax)

M_t_analyte_withIS.btz <- M_t_analyte_withIS %>% 
  left_join(btz_info, by = c("Compound.Name"= "SSA_name")) %>% 
  filter(!is.na(NIST_Name))%>% 
  mutate(My_Name = factor(My_Name,
                levels = c("2(3H)-Benzothiazolone", "Benzothiazole", "2-Benzothiazolamine, N-ethyl-", "2-(Methylmercapto)benzothiazole", "R-Benzothiazole 1", "R-Benzothiazole 2", "R-Benzothiazole 3", "R-Benzothiazole 4", "R-Benzothiazole 5", "R-Benzothiazole 6", "Benzothiazole, 2-phenyl- (1)", "2-o-Tolylbenzothiazole", "1,3-Di(2-benzothiazolyl)-\n1,3-bis(mercaptomethyl)-urea", "3-Ethylbenzothiazolin-2-thione"))) %>% 
  mutate(r_date_day = date(r_date))

just_btz_ssa_selected <- M_t_analyte_withIS.btz %>% 
  mutate(amt = vol_is_normnorm_ptnorm) %>% 
  filter(T_O_D == "Day") %>% 
  filter(r_date_day == "2019-07-24"| r_date_day == "2019-08-02") %>% 
  dplyr::select(My_Name, r_date_day, water_sol_mg_L, amt, btz_colors) %>% 
  mutate(date_type_factor = paste(r_date_day, "SSA", sep = " ")) %>% 
  filter(!is.na(My_Name)) %>% 
  filter(!is.na(water_sol_mg_L))




M_t_analyte_withIS.btz %>% 
  ggplot(aes(x = r_date, y = Volume, color = My_Name, fill = log(water_sol_mg_L), order = as.numeric(My_Name)))+
  geom_col(position = "fill", size = 1)+
  scale_fill_gradient(low = "white", high = "black", limits = c(0,8))+
  scale_colour_manual(values = btz_colors_ssa$btz_colors) +
  theme(legend.position = "bottom", legend.box="vertical", legend.margin=margin(), legend.text=element_text(size=8))+
    labs(color="", fill="log(Solubility)")+
  guides(color=guide_legend(nrow=4,byrow=TRUE))+
  ggtitle("Benzothiazoles in SSA")+
  ylab("Fraction Organic Btz Signal")+
  xlab("")+
  xlim(btzdatemin, btzdatemax)

M_t_analyte_withIS.btz %>% 
  ggplot(aes(x = r_date, y = Volume, color = My_Name, fill = log(water_sol_mg_L)))+
  geom_col(position = "stack", size = 1)+
  scale_fill_gradient(low = "white", high = "black", limits = c(0,8))+
  scale_colour_manual(values = btz_colors_ssa$btz_colors) +
  theme(legend.position = "bottom", legend.box="vertical", legend.margin=margin(), legend.text=element_text(size=8))+
    labs(color="", fill="log(Solubility)")+
  guides(color=guide_legend(nrow=4,byrow=TRUE))+
  ggtitle("Benzothiazoles in SSA")+
  ylab("Fraction Organic Btz Signal")+
  xlab("")+
  xlim(btzdatemin, btzdatemax)

M_t_analyte_withIS.btz %>% 
  ggplot(aes(x = r_date, y = vol_is_normnorm_ptnorm, color = My_Name, fill = log(water_sol_mg_L)))+
  geom_col(position = "stack", size = 1)+
  scale_fill_gradient(low = "white", high = "black", limits = c(0,8))+
  scale_colour_manual(values = btz_colors_ssa$btz_colors) +
  theme(legend.position = "bottom", legend.box="vertical", legend.margin=margin(), legend.text=element_text(size=8))+
    labs(color="", fill="log(Solubility)")+
  guides(color=guide_legend(nrow=4,byrow=TRUE))+
  ggtitle("Benzothiazoles in SSA")+
  ylab("IS_normalized_btzsig")+
  xlab("")+
  xlim(btzdatemin, btzdatemax)




btz_both_ts <- M_t_analyte_withIS.btz %>% 
  full_join(M_t_analyte_withIS_mdom.btz, by = c("r_date", "My_Name")) 
  

btz_both <- rbind(just_btz_mdom_selected, just_btz_ssa_selected) 

btz_both <- btz_both %>% 
  mutate(My_Name = factor(My_Name, levels = c("2(3H)-Benzothiazolone", "Benzothiazole", "3-Methyl-3H-benzothiazol-2-one", "4-Ethyl-5-methylthiazole", "2-Benzothiazolamine, N-ethyl-", "2-(Methylmercapto)benzothiazole", "R-Benzothiazole 1", "R-Benzothiazole 2", "R-Benzothiazole 3", "R-Benzothiazole 4", "R-Benzothiazole 5", "R-Benzothiazole 6", "Benzothiazole, 2-phenyl- (1)", "Benzothiazole, 2-phenyl- (2)", "2-o-Tolylbenzothiazole", "1,3-Di(2-benzothiazolyl)-\n1,3-bis(mercaptomethyl)-urea", "3-Ethylbenzothiazolin-2-thione"))) %>% 
  filter(!is.na(My_Name)) %>% 
  filter(!is.na(water_sol_mg_L))




btz_both %>% 
  ggplot(aes(x = date_type_factor, y = amt, color = My_Name, fill = log(water_sol_mg_L), order = as.numeric(My_Name)))+
  geom_col(position = "fill", size = 1, width = .2)+
  scale_fill_gradient(low = "white", high = "black", limits = c(0,8))+
  scale_colour_manual(values = btz_info$btz_colors) +
  theme(axis.text.x = element_text(angle = -45, vjust = 0, hjust=.1))+
    labs(color="", fill="log(Solubility)")+
  ggtitle("Benzothiazoles in MDOM and SSA")+
  ylab("Fraction Organic Btz Signal")+
  xlab("")

btz_info %>% 
  ggplot(aes(x = NIST_Name, y = water_sol_mg_L, color = My_Name))+
  geom_col()+ 
  scale_colour_manual(values = btz_info$btz_colors) +
  theme(legend.position = "bottom", legend.box="vertical", legend.margin=margin(), legend.text=element_text(size=8))+
    labs(color="", fill="log(Solubility)")+
  guides(color=guide_legend(nrow=4,byrow=TRUE))+
  ggtitle("Benzothiazoles in MDOM and SSA")+
  ylab("Fraction Organic Btz Signal")+
  xlab("")
  
  


```


```{r}
 btz_summarized_vols_ssa <- M_t_analyte_withIS.btz %>% 
  mutate(quant_abun = vol_is_normnorm_ptnorm * ssa_quant_factor) %>%
  group_by(Compound.Name) %>% 
  dplyr::summarise(mean_vol_quantified = mean(quant_abun, na.rm = TRUE)) %>% 
  left_join(btz_info, by = c("Compound.Name"= "SSA_name"))

 btz_summarized_vols_mdom <- M_t_analyte_withIS_mdom.btz %>% 
  mutate(quant_abun = vol_is_normnorm * mdom_quant_factor) %>%
  group_by(Compound.Name) %>% 
  dplyr::summarise(mean_vol_quantified = mean(quant_abun, na.rm = TRUE)) %>% 
  left_join(btz_info, by = c("Compound.Name"= "MDOM_name"))

 total_quant_btz_ssa <- sum(btz_summarized_vols_ssa$mean_vol_quantified)
 
 total_quant_btz_mdom <- sum(btz_summarized_vols_mdom$mean_vol_quantified)
 
 btz_summarized_vols_ssa <- btz_summarized_vols_ssa %>% 
   mutate(mean_vol_quant.n = mean_vol_quantified/total_quant_btz_ssa)
 
 btz_summarized_vols_mdom <- btz_summarized_vols_mdom %>% 
   mutate(mean_vol_quant.n = mean_vol_quantified/total_quant_btz_mdom)
 
ggplot(data = btz_summarized_vols_ssa)+
   geom_point(aes(x = "Sea Spray Aerosol", y = log(water_sol_mg_L), size = mean_vol_quant.n, color = Label_name, fill = Label_name.sp), shape = 21)+
   geom_point(data = btz_summarized_vols_mdom, aes(x = "DOM", y = log(water_sol_mg_L), size = mean_vol_quant.n, color = Label_name, fill = Label_name.sp), shape = 21)+
   theme_bw()+
   scale_color_manual(values = c("black", "blue", "red"))+
  scale_fill_manual(values = c("yellow", "green1", "white"))+
   ylab("log(Solubility(mg/L))")+
   xlab("")+
  ggtitle("Solubility and Molecular Overlap\n of DOM and SSA Benzothiazoles")+
  guides(fill=guide_legend(title="Notable Compounds"), color=guide_legend(title=""), size=guide_legend(title="Fraction Benzothiazole\nOrganic Pool") )
   



```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
